### ISSUE TITLE
GitLab release with composer dependencies

### ISSUE THREAD

**Issue by noplanman** [afragen/github-updater#819]
I'm basically looking for a way to use GitLab CI to build a production plugin (`composer install --no-dev`) and zip the clean file structure without any development stuff.

After many failed attempts using `GitLab CI Job: build-plugin` and `Release Asset: true` I'm coming here to figure out what I'm doing wrong...

What exactly needs to be built as an artifact for GitHub Updater to install it successfully?

Here is my simple example of a `.gitlab-ci.yml` file:
```yaml
build-plugin:
  only:
  - tags
  image: php:7.3-cli-alpine
  script:
  - apk -U add git zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --no-dev --no-interaction
  # Zip only required files
  - zip -r /tmp/plugin.zip . -i@.ziponly
  # Delete everything
  - rm -rf $(ls -A)
  # Unzip only necessary files back here for the artifact itself
  - unzip /tmp/plugin.zip -d .
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
    paths: [.]
    expire_in: 1 week
```
(`.ziponly` is a file that contains a list of files that are required for the production plugin)

This creates an artifact with the correct name: `<repo>-<tag>.zip`

But when updating, it breaks after creating the first folder and that folder stays empty:
```sh
- plugin.php
- vendor (empty)
```
What it should be:
```sh
- plugin.php
- lib
  - (all libs etc.)
- vendor
  - (all vendor files)
```

Any guidance would be much appreciated, thanks :smiley:
